import { createApiKey } from '../utils/index.js'

export default {
  allowCache: false,
  apiKey: createApiKey(),
  corsAllowCredentials: true, // TODO no CLI option
  corsAllowHeaders: 'accept,content-type,x-api-key,authorization',
  corsAllowOrigin: '*',
  corsExposedHeaders: 'WWW-Authenticate,Server-Authorization',
  disableCookieValidation: false,
  disableScheduledEvents: false,
  dockerExposePort: '',
  dockerHost: 'localhost',
  dockerHostServicePath: null,
  dockerImagePull: true,
  dockerLambdaStayOpen: true,
  dockerLambdaWatch: true,
  dockerNetwork: null,
  dockerReadOnly: true,
  dockerRuntimeDebug: false,
  enforceSecureCookies: false,
  functionCleanupIdleTimeSeconds: 60,
  hideStackTraces: false,
  host: 'localhost',
  httpPort: 3000,
  httpsProtocol: '',
  lambdaHost: 'localhost',
  lambdaPort: 3002,
  layersDir: null,
  noAuth: false,
  noPrependStageInUrl: false,
  noStripTrailingSlashInUrl: false,
  noTimeout: false,
  prefix: '',
  printOutput: false,
  resourceRoutes: false,
  useChildProcesses: false,
  useDocker: false,
  useInProcess: false,
  webSocketHardTimeout: 7200,
  websocketHost: 'localhost',
  webSocketIdleTimeout: 600,
  websocketPort: 3001,
}
